// Generated by npm run generate:cipher-bank. Do not edit by hand.
export default {
  "w001": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "F",
      "S"
    ]
  },
  "w067": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "L",
      "M"
    ]
  },
  "w181": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "B",
      "A"
    ]
  },
  "w006": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "B",
      "A"
    ]
  },
  "w189": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "B",
      "E"
    ]
  },
  "w071": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "B",
      "L"
    ]
  },
  "w002": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "B",
      "R"
    ]
  },
  "w069": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "B",
      "O"
    ]
  },
  "w290": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "C",
      "L"
    ]
  },
  "w129": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "C",
      "V"
    ]
  },
  "w238": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "D",
      "V"
    ]
  },
  "w250": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "D",
      "A"
    ]
  },
  "w289": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "F",
      "A"
    ]
  },
  "w130": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "H",
      "L"
    ]
  },
  "w178": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "C",
      "K"
    ]
  },
  "w080": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "C",
      "R"
    ]
  },
  "w083": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "C",
      "I"
    ]
  },
  "w182": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "C",
      "R"
    ]
  },
  "w013": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "C",
      "A"
    ]
  },
  "w003": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "D",
      "E"
    ]
  },
  "w240": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "G",
      "A"
    ]
  },
  "w291": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "H",
      "P"
    ]
  },
  "w234": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "J",
      "M"
    ]
  },
  "w131": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "L",
      "K"
    ]
  },
  "w123": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "L",
      "A"
    ]
  },
  "w288": {
    "positions": [
      1,
      3
    ],
    "letters": [
      "L",
      "V"
    ]
  },
  "w296": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "A",
      "G",
      "R"
    ]
  },
  "w192": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "A",
      "P",
      "E"
    ]
  },
  "w142": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "B",
      "A",
      "H"
    ]
  },
  "w036": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "B",
      "S",
      "N"
    ]
  },
  "w146": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "B",
      "O",
      "M"
    ]
  },
  "w303": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "B",
      "A",
      "E"
    ]
  },
  "w193": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "B",
      "E",
      "D"
    ]
  },
  "w093": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "B",
      "O",
      "M"
    ]
  },
  "w254": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "C",
      "T",
      "H"
    ]
  },
  "w085": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "C",
      "A",
      "R"
    ]
  },
  "w252": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "C",
      "I",
      "B"
    ]
  },
  "w030": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "E",
      "G",
      "E"
    ]
  },
  "w140": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "C",
      "O",
      "D"
    ]
  },
  "w144": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "C",
      "R",
      "L"
    ]
  },
  "w258": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "C",
      "A",
      "L"
    ]
  },
  "w251": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "D",
      "N",
      "E"
    ]
  },
  "w199": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "G",
      "A",
      "E"
    ]
  },
  "w297": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "G",
      "I",
      "F"
    ]
  },
  "w300": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "H",
      "P",
      "Y"
    ]
  },
  "w196": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "H",
      "N",
      "Y"
    ]
  },
  "w026": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "H",
      "R",
      "E"
    ]
  },
  "w028": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "H",
      "E",
      "A"
    ]
  },
  "w087": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "K",
      "I",
      "E"
    ]
  },
  "w089": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "P",
      "P",
      "R"
    ]
  },
  "w305": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "A",
      "A",
      "E"
    ]
  },
  "w206": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "B",
      "N",
      "N"
    ]
  },
  "w104": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "B",
      "S",
      "E"
    ]
  },
  "w040": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "B",
      "A",
      "E"
    ]
  },
  "w048": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "B",
      "E",
      "L"
    ]
  },
  "w098": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "B",
      "T",
      "L"
    ]
  },
  "w156": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "B",
      "A",
      "C"
    ]
  },
  "w216": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "B",
      "T",
      "E"
    ]
  },
  "w153": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "C",
      "N",
      "O"
    ]
  },
  "w270": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "F",
      "M",
      "L"
    ]
  },
  "w306": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "G",
      "O",
      "M"
    ]
  },
  "w271": {
    "positions": [
      1,
      3,
      5
    ],
    "letters": [
      "J",
      "G",
      "L"
    ]
  },
  "w308": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "A",
      "X",
      "O",
      "S"
    ]
  },
  "w223": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "A",
      "O",
      "A",
      "O"
    ]
  },
  "w220": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "B",
      "S",
      "U",
      "T"
    ]
  },
  "w107": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "B",
      "A",
      "K",
      "T"
    ]
  },
  "w161": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "B",
      "O",
      "S",
      "M"
    ]
  },
  "w165": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "B",
      "U",
      "D",
      "R"
    ]
  },
  "w311": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "C",
      "R",
      "O",
      "S"
    ]
  },
  "w111": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "C",
      "S",
      "I",
      "N"
    ]
  },
  "w049": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "D",
      "L",
      "H",
      "N"
    ]
  },
  "w051": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "G",
      "R",
      "F",
      "E"
    ]
  },
  "w281": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "S",
      "U",
      "G",
      "E"
    ]
  },
  "w280": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "S",
      "A",
      "K",
      "E"
    ]
  },
  "w060": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "A",
      "T",
      "L",
      "P"
    ]
  },
  "w114": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "B",
      "C",
      "P",
      "C"
    ]
  },
  "w227": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "B",
      "O",
      "C",
      "L"
    ]
  },
  "w229": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "D",
      "U",
      "H",
      "U"
    ]
  },
  "w062": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "E",
      "E",
      "H",
      "N"
    ]
  },
  "w317": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "G",
      "A",
      "E",
      "U"
    ]
  },
  "w171": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "H",
      "L",
      "S",
      "D"
    ]
  },
  "w115": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "K",
      "Y",
      "O",
      "R"
    ]
  },
  "w166": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "M",
      "U",
      "T",
      "I"
    ]
  },
  "w283": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "S",
      "R",
      "M",
      "L"
    ]
  },
  "w284": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "S",
      "R",
      "N",
      "L"
    ]
  },
  "w316": {
    "positions": [
      1,
      3,
      5,
      7
    ],
    "letters": [
      "S",
      "R",
      "R",
      "S"
    ]
  }
};
