// Generated by npm run generate:word-banks. Do not edit by hand.
export default {
  "w001": {
  "letters": [
    "I",
    "H"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w002": {
  "letters": [
    "I",
    "D"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w003": {
  "letters": [
    "E",
    "R"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w004": {
  "letters": [
    "O",
    "F"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w005": {
  "letters": [
    "I",
    "N"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w006": {
  "letters": [
    "E",
    "R"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w007": {
  "letters": [
    "O",
    "T"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w008": {
  "letters": [
    "U",
    "K"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w009": {
  "letters": [
    "R",
    "G"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w010": {
  "letters": [
    "A",
    "K"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w011": {
  "letters": [
    "O",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w012": {
  "letters": [
    "E",
    "L"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w013": {
  "letters": [
    "R",
    "B"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w014": {
  "letters": [
    "W",
    "N"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w015": {
  "letters": [
    "O",
    "D"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w016": {
  "letters": [
    "U",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w017": {
  "letters": [
    "Y",
    "X"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w018": {
  "letters": [
    "U",
    "A"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w019": {
  "letters": [
    "O",
    "S"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w020": {
  "letters": [
    "I",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w021": {
  "letters": [
    "E",
    "R"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w022": {
  "letters": [
    "N",
    "K"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w023": {
  "letters": [
    "H",
    "R"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w024": {
  "letters": [
    "H",
    "L"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w025": {
  "letters": [
    "A",
    "D"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w026": {
  "letters": [
    "O",
    "S"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w027": {
  "letters": [
    "H",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w028": {
  "letters": [
    "Y",
    "N"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w029": {
  "letters": [
    "T",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "vowel"
  }
},
  "w030": {
  "letters": [
    "A",
    "L"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "vowel"
  }
},
  "w031": {
  "letters": [
    "O",
    "I"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w032": {
  "letters": [
    "L",
    "T"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w033": {
  "letters": [
    "A",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w034": {
  "letters": [
    "O",
    "S"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w035": {
  "letters": [
    "I",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w036": {
  "letters": [
    "I",
    "O"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w037": {
  "letters": [
    "A",
    "B",
    "T"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w038": {
  "letters": [
    "O",
    "K",
    "Y"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w039": {
  "letters": [
    "U",
    "T",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w040": {
  "letters": [
    "E",
    "V",
    "R"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w041": {
  "letters": [
    "E",
    "S",
    "L"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w042": {
  "letters": [
    "A",
    "U",
    "R"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w043": {
  "letters": [
    "O",
    "O",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w044": {
  "letters": [
    "Y",
    "T",
    "R"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "vowel"
  }
},
  "w045": {
  "letters": [
    "O",
    "C",
    "N"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w046": {
  "letters": [
    "G",
    "A",
    "A"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "vowel"
  }
},
  "w047": {
  "letters": [
    "P",
    "D",
    "R"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w048": {
  "letters": [
    "E",
    "T",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w049": {
  "letters": [
    "O",
    "P",
    "I"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w050": {
  "letters": [
    "E",
    "G",
    "I"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w051": {
  "letters": [
    "I",
    "A",
    "F"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w052": {
  "letters": [
    "A",
    "S",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w053": {
  "letters": [
    "E",
    "P",
    "R"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w054": {
  "letters": [
    "C",
    "O",
    "U"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "vowel"
  }
},
  "w055": {
  "letters": [
    "A",
    "T",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w056": {
  "letters": [
    "A",
    "L",
    "R"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w057": {
  "letters": [
    "O",
    "I",
    "L"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w058": {
  "letters": [
    "A",
    "G",
    "R",
    "O"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w059": {
  "letters": [
    "E",
    "G",
    "H",
    "G"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w060": {
  "letters": [
    "N",
    "E",
    "O",
    "E"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "vowel"
  }
},
  "w061": {
  "letters": [
    "L",
    "M",
    "N",
    "O"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w062": {
  "letters": [
    "L",
    "P",
    "A",
    "T"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "vowel"
  }
},
  "w063": {
  "letters": [
    "R",
    "C",
    "D",
    "L"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 4,
    "firstSound": "consonant"
  }
},
  "w064": {
  "letters": [
    "U",
    "T",
    "R",
    "L"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w065": {
  "letters": [
    "R",
    "A",
    "I",
    "L"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 4,
    "firstSound": "vowel"
  }
},
  "w066": {
  "letters": [
    "R",
    "N",
    "U",
    "A"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 4,
    "firstSound": "vowel"
  }
},
  "w067": {
  "letters": [
    "A",
    "P"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w068": {
  "letters": [
    "E",
    "K"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w069": {
  "letters": [
    "O",
    "K"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w070": {
  "letters": [
    "O",
    "R"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w071": {
  "letters": [
    "E",
    "L"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w072": {
  "letters": [
    "I",
    "G"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w073": {
  "letters": [
    "O",
    "K"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w074": {
  "letters": [
    "R",
    "M"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w075": {
  "letters": [
    "L",
    "G"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w076": {
  "letters": [
    "O",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w077": {
  "letters": [
    "O",
    "K"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w078": {
  "letters": [
    "A",
    "L"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w079": {
  "letters": [
    "I",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w080": {
  "letters": [
    "A",
    "T"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w081": {
  "letters": [
    "O",
    "K"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w082": {
  "letters": [
    "A",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w083": {
  "letters": [
    "O",
    "N"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w084": {
  "letters": [
    "O",
    "B"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w085": {
  "letters": [
    "H",
    "I"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w086": {
  "letters": [
    "A",
    "L"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w087": {
  "letters": [
    "N",
    "F"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w088": {
  "letters": [
    "H",
    "N"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w089": {
  "letters": [
    "A",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w090": {
  "letters": [
    "L",
    "T"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w091": {
  "letters": [
    "O",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w092": {
  "letters": [
    "T",
    "V"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w093": {
  "letters": [
    "R",
    "O"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w094": {
  "letters": [
    "P",
    "O"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w095": {
  "letters": [
    "A",
    "C"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w096": {
  "letters": [
    "A",
    "I"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w097": {
  "letters": [
    "E",
    "C",
    "L"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w098": {
  "letters": [
    "O",
    "T",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w099": {
  "letters": [
    "A",
    "D",
    "R"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w100": {
  "letters": [
    "I",
    "L",
    "W"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w101": {
  "letters": [
    "I",
    "D",
    "W"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w102": {
  "letters": [
    "U",
    "K",
    "T"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w103": {
  "letters": [
    "I",
    "R",
    "R"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w104": {
  "letters": [
    "A",
    "K",
    "T"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w105": {
  "letters": [
    "A",
    "E",
    "A"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w106": {
  "letters": [
    "A",
    "L",
    "T"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w107": {
  "letters": [
    "L",
    "N",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w108": {
  "letters": [
    "H",
    "S",
    "L"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w109": {
  "letters": [
    "O",
    "R",
    "A"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w110": {
  "letters": [
    "A",
    "T",
    "R"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w111": {
  "letters": [
    "U",
    "H",
    "O"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w112": {
  "letters": [
    "A",
    "R",
    "N"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "vowel"
  }
},
  "w113": {
  "letters": [
    "T",
    "C",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w114": {
  "letters": [
    "A",
    "K",
    "A",
    "K"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w115": {
  "letters": [
    "E",
    "B",
    "A",
    "D"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w116": {
  "letters": [
    "E",
    "K",
    "A",
    "E"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w117": {
  "letters": [
    "M",
    "R",
    "L",
    "A"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "vowel"
  }
},
  "w118": {
  "letters": [
    "U",
    "T",
    "A",
    "E"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w119": {
  "letters": [
    "N",
    "P",
    "A",
    "K"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w120": {
  "letters": [
    "E",
    "E",
    "H",
    "N"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w121": {
  "letters": [
    "T",
    "I",
    "C",
    "S"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w122": {
  "letters": [
    "E",
    "E",
    "C",
    "P"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w123": {
  "letters": [
    "E",
    "F"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w124": {
  "letters": [
    "R",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w125": {
  "letters": [
    "O",
    "K"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w126": {
  "letters": [
    "I",
    "D"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w127": {
  "letters": [
    "A",
    "N"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w128": {
  "letters": [
    "N",
    "W"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w129": {
  "letters": [
    "A",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w130": {
  "letters": [
    "I",
    "L"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w131": {
  "letters": [
    "A",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w132": {
  "letters": [
    "O",
    "D"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w133": {
  "letters": [
    "U",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w134": {
  "letters": [
    "E",
    "F"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w135": {
  "letters": [
    "I",
    "T"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w136": {
  "letters": [
    "I",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w137": {
  "letters": [
    "O",
    "S"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w138": {
  "letters": [
    "I",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w139": {
  "letters": [
    "C",
    "A"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "vowel"
  }
},
  "w140": {
  "letters": [
    "L",
    "U"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w141": {
  "letters": [
    "T",
    "R"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w142": {
  "letters": [
    "E",
    "C"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w143": {
  "letters": [
    "T",
    "N"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w144": {
  "letters": [
    "O",
    "A"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w145": {
  "letters": [
    "R",
    "S"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w146": {
  "letters": [
    "L",
    "O"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w147": {
  "letters": [
    "R",
    "S"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w148": {
  "letters": [
    "O",
    "E",
    "T"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w149": {
  "letters": [
    "E",
    "E",
    "T"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w150": {
  "letters": [
    "A",
    "L",
    "Y"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w151": {
  "letters": [
    "E",
    "D",
    "W"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w152": {
  "letters": [
    "E",
    "S",
    "R"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w153": {
  "letters": [
    "A",
    "Y",
    "N"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w154": {
  "letters": [
    "S",
    "A",
    "D"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "vowel"
  }
},
  "w155": {
  "letters": [
    "E",
    "B",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w156": {
  "letters": [
    "R",
    "N",
    "H"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w157": {
  "letters": [
    "U",
    "S",
    "T"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w158": {
  "letters": [
    "P",
    "I",
    "G"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w159": {
  "letters": [
    "L",
    "C",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w160": {
  "letters": [
    "O",
    "C",
    "N"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w161": {
  "letters": [
    "L",
    "S",
    "O"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w162": {
  "letters": [
    "A",
    "N",
    "O"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w163": {
  "letters": [
    "R",
    "Z",
    "L"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w164": {
  "letters": [
    "H",
    "N",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w165": {
  "letters": [
    "O",
    "L",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w166": {
  "letters": [
    "O",
    "N",
    "A",
    "N"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w167": {
  "letters": [
    "U",
    "L",
    "G",
    "T"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w168": {
  "letters": [
    "W",
    "L",
    "G",
    "T"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w169": {
  "letters": [
    "E",
    "S",
    "E",
    "L"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w170": {
  "letters": [
    "I",
    "E",
    "B",
    "D"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w171": {
  "letters": [
    "I",
    "L",
    "I",
    "E"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w172": {
  "letters": [
    "N",
    "W",
    "A",
    "L"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w173": {
  "letters": [
    "H",
    "R",
    "P",
    "O"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w174": {
  "letters": [
    "A",
    "E",
    "F",
    "L"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w175": {
  "letters": [
    "V",
    "L",
    "N",
    "H"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "vowel"
  }
},
  "w176": {
  "letters": [
    "R",
    "F",
    "W",
    "O"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w177": {
  "letters": [
    "O",
    "N",
    "I",
    "H"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w178": {
  "letters": [
    "A",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w179": {
  "letters": [
    "O",
    "P"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w180": {
  "letters": [
    "I",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w181": {
  "letters": [
    "E",
    "N"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w182": {
  "letters": [
    "O",
    "N"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w183": {
  "letters": [
    "L",
    "M"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w184": {
  "letters": [
    "I",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w185": {
  "letters": [
    "E",
    "R"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w186": {
  "letters": [
    "I",
    "K"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w187": {
  "letters": [
    "E",
    "T"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w188": {
  "letters": [
    "A",
    "O"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w189": {
  "letters": [
    "E",
    "F"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w190": {
  "letters": [
    "O",
    "K"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w191": {
  "letters": [
    "I",
    "T"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w192": {
  "letters": [
    "P",
    "L"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "vowel"
  }
},
  "w193": {
  "letters": [
    "R",
    "A"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w194": {
  "letters": [
    "A",
    "T"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w195": {
  "letters": [
    "I",
    "Z"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w196": {
  "letters": [
    "O",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w197": {
  "letters": [
    "E",
    "O"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w198": {
  "letters": [
    "A",
    "G"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w199": {
  "letters": [
    "R",
    "P"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w200": {
  "letters": [
    "E",
    "C"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w201": {
  "letters": [
    "A",
    "A"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w202": {
  "letters": [
    "R",
    "V"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w203": {
  "letters": [
    "U",
    "A"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w204": {
  "letters": [
    "N",
    "O"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "vowel"
  }
},
  "w205": {
  "letters": [
    "H",
    "A"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w206": {
  "letters": [
    "A",
    "A",
    "A"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w207": {
  "letters": [
    "A",
    "R",
    "T"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w208": {
  "letters": [
    "H",
    "R",
    "Y"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w209": {
  "letters": [
    "A",
    "N",
    "T"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w210": {
  "letters": [
    "I",
    "K",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w211": {
  "letters": [
    "O",
    "D",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w212": {
  "letters": [
    "O",
    "A",
    "O"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w213": {
  "letters": [
    "O",
    "A",
    "O"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w214": {
  "letters": [
    "O",
    "U",
    "T"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w215": {
  "letters": [
    "E",
    "E",
    "Y"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w216": {
  "letters": [
    "U",
    "T",
    "R"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w217": {
  "letters": [
    "A",
    "C",
    "K"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w218": {
  "letters": [
    "O",
    "C",
    "R"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w219": {
  "letters": [
    "R",
    "T",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w220": {
  "letters": [
    "I",
    "C",
    "I"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w221": {
  "letters": [
    "A",
    "M",
    "A"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "vowel"
  }
},
  "w222": {
  "letters": [
    "A",
    "B",
    "G"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w223": {
  "letters": [
    "V",
    "C",
    "D"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 4,
    "firstSound": "vowel"
  }
},
  "w224": {
  "letters": [
    "U",
    "P",
    "I"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w225": {
  "letters": [
    "U",
    "C",
    "K"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w226": {
  "letters": [
    "A",
    "D",
    "I",
    "H"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w227": {
  "letters": [
    "R",
    "C",
    "O",
    "I"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w228": {
  "letters": [
    "E",
    "T",
    "A",
    "L"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w229": {
  "letters": [
    "O",
    "G",
    "N",
    "T"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w230": {
  "letters": [
    "I",
    "E",
    "P",
    "L"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w231": {
  "letters": [
    "L",
    "E",
    "E",
    "R"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w232": {
  "letters": [
    "A",
    "S",
    "R",
    "L"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 4,
    "firstSound": "consonant"
  }
},
  "w233": {
  "letters": [
    "H",
    "C",
    "L",
    "T"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w234": {
  "letters": [
    "U",
    "P"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w235": {
  "letters": [
    "W",
    "M"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w236": {
  "letters": [
    "A",
    "K"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w237": {
  "letters": [
    "P",
    "N"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w238": {
  "letters": [
    "I",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w239": {
  "letters": [
    "I",
    "K"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w240": {
  "letters": [
    "R",
    "B"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w241": {
  "letters": [
    "U",
    "H"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w242": {
  "letters": [
    "U",
    "L"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w243": {
  "letters": [
    "E",
    "P"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w244": {
  "letters": [
    "I",
    "G"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w245": {
  "letters": [
    "A",
    "K"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w246": {
  "letters": [
    "I",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w247": {
  "letters": [
    "K",
    "P"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w248": {
  "letters": [
    "A",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w249": {
  "letters": [
    "U",
    "H"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w250": {
  "letters": [
    "R",
    "W"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w251": {
  "letters": [
    "A",
    "C"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w252": {
  "letters": [
    "L",
    "M"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w253": {
  "letters": [
    "H",
    "O"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w254": {
  "letters": [
    "A",
    "C"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w255": {
  "letters": [
    "H",
    "U"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w256": {
  "letters": [
    "A",
    "G"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w257": {
  "letters": [
    "L",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w258": {
  "letters": [
    "R",
    "W"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w259": {
  "letters": [
    "M",
    "L"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w260": {
  "letters": [
    "R",
    "T"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w261": {
  "letters": [
    "T",
    "R"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w262": {
  "letters": [
    "N",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w263": {
  "letters": [
    "W",
    "N"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w264": {
  "letters": [
    "O",
    "N"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w265": {
  "letters": [
    "P",
    "I",
    "T"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w266": {
  "letters": [
    "I",
    "G",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w267": {
  "letters": [
    "U",
    "B",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w268": {
  "letters": [
    "C",
    "E",
    "M"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w269": {
  "letters": [
    "A",
    "D",
    "R"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w270": {
  "letters": [
    "U",
    "B",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w271": {
  "letters": [
    "I",
    "G",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w272": {
  "letters": [
    "I",
    "B",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w273": {
  "letters": [
    "A",
    "D",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w274": {
  "letters": [
    "Q",
    "I",
    "M"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w275": {
  "letters": [
    "I",
    "T",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w276": {
  "letters": [
    "H",
    "S",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w277": {
  "letters": [
    "T",
    "E",
    "C"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w278": {
  "letters": [
    "T",
    "M",
    "L"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w279": {
  "letters": [
    "R",
    "S",
    "L"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w280": {
  "letters": [
    "P",
    "R",
    "L"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w281": {
  "letters": [
    "N",
    "G",
    "L"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w282": {
  "letters": [
    "T",
    "U",
    "G",
    "E"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w283": {
  "letters": [
    "C",
    "A",
    "B",
    "E"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w284": {
  "letters": [
    "P",
    "I",
    "K",
    "E"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w285": {
  "letters": [
    "A",
    "T",
    "H",
    "E"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w286": {
  "letters": [
    "E",
    "E",
    "R",
    "T"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w287": {
  "letters": [
    "U",
    "R",
    "N",
    "E"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w288": {
  "letters": [
    "O",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w289": {
  "letters": [
    "E",
    "R"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w290": {
  "letters": [
    "A",
    "M"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w291": {
  "letters": [
    "O",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w292": {
  "letters": [
    "A",
    "N"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w293": {
  "letters": [
    "L",
    "D"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w294": {
  "letters": [
    "I",
    "D"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w295": {
  "letters": [
    "R",
    "D"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w296": {
  "letters": [
    "N",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "vowel"
  }
},
  "w297": {
  "letters": [
    "R",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w298": {
  "letters": [
    "A",
    "I"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w299": {
  "letters": [
    "O",
    "R"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w300": {
  "letters": [
    "A",
    "P"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w301": {
  "letters": [
    "A",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "vowel"
  }
},
  "w302": {
  "letters": [
    "I",
    "E"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w303": {
  "letters": [
    "R",
    "V"
  ],
  "positions": [
    2,
    4
  ],
  "hints": {
    "syllables": 1,
    "firstSound": "consonant"
  }
},
  "w304": {
  "letters": [
    "O",
    "R",
    "W"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w305": {
  "letters": [
    "M",
    "Z",
    "D"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "vowel"
  }
},
  "w306": {
  "letters": [
    "L",
    "O",
    "Y"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w307": {
  "letters": [
    "O",
    "F",
    "L"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w308": {
  "letters": [
    "N",
    "I",
    "U"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "vowel"
  }
},
  "w309": {
  "letters": [
    "E",
    "L",
    "U"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w310": {
  "letters": [
    "E",
    "V",
    "U"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w311": {
  "letters": [
    "U",
    "I",
    "U"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w312": {
  "letters": [
    "N",
    "I",
    "T"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "vowel"
  }
},
  "w313": {
  "letters": [
    "E",
    "I",
    "H"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w314": {
  "letters": [
    "A",
    "N",
    "S"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w315": {
  "letters": [
    "X",
    "I",
    "E"
  ],
  "positions": [
    2,
    4,
    6
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "vowel"
  }
},
  "w316": {
  "letters": [
    "U",
    "P",
    "I",
    "E"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 2,
    "firstSound": "consonant"
  }
},
  "w317": {
  "letters": [
    "R",
    "T",
    "F",
    "L"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w318": {
  "letters": [
    "E",
    "L",
    "U",
    "Y"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w319": {
  "letters": [
    "O",
    "F",
    "D",
    "N"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w320": {
  "letters": [
    "A",
    "P",
    "N",
    "S"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
},
  "w321": {
  "letters": [
    "R",
    "T",
    "T",
    "D"
  ],
  "positions": [
    2,
    4,
    6,
    8
  ],
  "hints": {
    "syllables": 3,
    "firstSound": "consonant"
  }
}
};
