// Public, shared level metadata. Deliberately contains no plaintext letters
// and no plaintext answer — only a SHA-256 hash of each answer, so a
// completed guess can be verified client-side without ever shipping the
// word itself in this shared file. See level-NN.a.js / level-NN.b.js for
// the actual per-role glyph data, which are only ever fetched by the
// matching role's code path.
export const LEVELS = [
  {
    "id": "level-01",
    "difficulty": 1,
    "length": 4,
    "iconPalette": [
      "shape:line",
      "shape:curve",
      "shape:loop",
      "shape:cross",
      "shape:dot",
      "pos:first",
      "pos:last",
      "pos:before",
      "pos:after",
      "pos:between",
      "count:1",
      "count:2",
      "count:3",
      "cmp:same",
      "cmp:diff",
      "cat:animal",
      "cat:object",
      "cat:nature",
      "cat:action",
      "cat:food",
      "cat:feeling",
      "meta:confirm",
      "meta:reject",
      "meta:question"
    ],
    "maxBoardIcons": null,
    "answerHash": "44864ee65edd56c0fcfa7ff97b88563969d5099faf5d2f0e1a89a8252370f819"
  },
  {
    "id": "level-02",
    "difficulty": 2,
    "length": 4,
    "iconPalette": [
      "shape:line",
      "shape:curve",
      "shape:loop",
      "shape:cross",
      "shape:dot",
      "pos:first",
      "pos:last",
      "pos:before",
      "pos:after",
      "pos:between",
      "count:1",
      "count:2",
      "count:3",
      "cmp:same",
      "cmp:diff",
      "cat:animal",
      "cat:object",
      "cat:nature",
      "cat:action",
      "cat:food",
      "cat:feeling",
      "meta:confirm",
      "meta:reject",
      "meta:question"
    ],
    "maxBoardIcons": null,
    "answerHash": "d92d4d0fe9fe4d443ff7257759fc4e048670eb73f6644dd34adcc854eba62d22"
  },
  {
    "id": "level-03",
    "difficulty": 3,
    "length": 5,
    "iconPalette": [
      "shape:line",
      "shape:curve",
      "shape:loop",
      "shape:cross",
      "shape:dot",
      "pos:first",
      "pos:last",
      "pos:before",
      "pos:after",
      "pos:between",
      "count:1",
      "count:2",
      "count:3",
      "count:4",
      "cmp:same",
      "cmp:diff",
      "cat:animal",
      "cat:object",
      "cat:nature",
      "cat:action",
      "cat:food",
      "cat:feeling",
      "meta:confirm",
      "meta:reject",
      "meta:question"
    ],
    "maxBoardIcons": 20,
    "answerHash": "92297327e6e2fc4572c14a9d10c18d11e4c6a9701b1bcd2bcac9cfb64c871f9b"
  },
  {
    "id": "level-04",
    "difficulty": 4,
    "length": 5,
    "iconPalette": [
      "shape:line",
      "shape:curve",
      "shape:loop",
      "shape:cross",
      "shape:dot",
      "pos:first",
      "pos:last",
      "pos:before",
      "pos:after",
      "pos:between",
      "count:1",
      "count:2",
      "count:3",
      "count:4",
      "count:5",
      "cmp:same",
      "cmp:diff",
      "cat:animal",
      "cat:object",
      "cat:nature",
      "cat:action",
      "cat:food",
      "cat:feeling",
      "meta:confirm",
      "meta:reject",
      "meta:question"
    ],
    "maxBoardIcons": 18,
    "answerHash": "55562347f437d65829303cf6307e71acf8b84a020989dd218f31586eeafd01a9"
  },
  {
    "id": "level-05",
    "difficulty": 5,
    "length": 5,
    "iconPalette": [
      "shape:line",
      "shape:curve",
      "shape:loop",
      "shape:cross",
      "shape:dot",
      "pos:first",
      "pos:last",
      "pos:before",
      "pos:after",
      "pos:between",
      "count:1",
      "count:2",
      "count:3",
      "count:4",
      "count:5",
      "cmp:same",
      "cmp:diff",
      "cat:animal",
      "cat:object",
      "cat:nature",
      "cat:action",
      "cat:food",
      "meta:confirm",
      "meta:reject",
      "meta:question"
    ],
    "maxBoardIcons": 16,
    "answerHash": "ca14f38c2d0051252c054d972a75e800fea6d7b5b11b9e3a45aaa6c2b16953b8"
  },
  {
    "id": "level-06",
    "difficulty": 6,
    "length": 6,
    "iconPalette": [
      "shape:line",
      "shape:curve",
      "shape:loop",
      "shape:cross",
      "shape:dot",
      "pos:first",
      "pos:last",
      "pos:before",
      "pos:after",
      "count:1",
      "count:2",
      "count:3",
      "count:4",
      "count:5",
      "cmp:same",
      "cmp:diff",
      "cat:animal",
      "cat:object",
      "cat:nature",
      "cat:action",
      "cat:food",
      "meta:confirm",
      "meta:reject",
      "meta:question"
    ],
    "maxBoardIcons": 16,
    "answerHash": "ff005b55b58c67918958c486ca49dd51ff3d784ccc1bb0079c53c4be454979e1"
  },
  {
    "id": "level-07",
    "difficulty": 7,
    "length": 6,
    "iconPalette": [
      "shape:line",
      "shape:curve",
      "shape:loop",
      "shape:cross",
      "shape:dot",
      "pos:first",
      "pos:last",
      "pos:before",
      "pos:after",
      "count:1",
      "count:2",
      "count:3",
      "count:4",
      "count:5",
      "cmp:same",
      "cmp:diff",
      "cat:animal",
      "cat:object",
      "cat:nature",
      "cat:action",
      "cat:food",
      "meta:confirm",
      "meta:reject"
    ],
    "maxBoardIcons": 14,
    "answerHash": "c966b157efac204e6062215b61111127965212a6621c186465813e68fd1dd45a"
  },
  {
    "id": "level-08",
    "difficulty": 8,
    "length": 7,
    "iconPalette": [
      "shape:line",
      "shape:curve",
      "shape:loop",
      "shape:dot",
      "pos:first",
      "pos:last",
      "pos:before",
      "pos:after",
      "count:1",
      "count:2",
      "count:3",
      "count:4",
      "count:5",
      "cmp:same",
      "cmp:diff",
      "cat:animal",
      "cat:object",
      "cat:nature",
      "cat:action",
      "cat:food",
      "meta:confirm",
      "meta:reject"
    ],
    "maxBoardIcons": 12,
    "answerHash": "5382a6e244cb5e9ccfb91cc6bda26ad9d8d08273dde3128068def516f073a018"
  },
  {
    "id": "level-09",
    "difficulty": 9,
    "length": 7,
    "iconPalette": [
      "shape:line",
      "shape:curve",
      "shape:loop",
      "pos:first",
      "pos:last",
      "pos:before",
      "pos:after",
      "count:1",
      "count:2",
      "count:3",
      "count:4",
      "cmp:same",
      "cmp:diff",
      "cat:animal",
      "cat:object",
      "cat:nature",
      "cat:action",
      "cat:food",
      "meta:confirm",
      "meta:reject"
    ],
    "maxBoardIcons": 10,
    "answerHash": "aca4fee155368758392aca3a58e5704c8650173981160328f27181fcf67b68e4"
  },
  {
    "id": "level-10",
    "difficulty": 10,
    "length": 8,
    "iconPalette": [
      "shape:line",
      "shape:curve",
      "shape:loop",
      "pos:first",
      "pos:last",
      "pos:before",
      "pos:after",
      "count:1",
      "count:2",
      "count:3",
      "cmp:same",
      "cmp:diff",
      "cat:animal",
      "cat:object",
      "cat:nature",
      "cat:action",
      "cat:food",
      "meta:confirm",
      "meta:reject"
    ],
    "maxBoardIcons": 8,
    "answerHash": "eab4fd789f4d46296712db9889958bd3188f2bc3a822c816dd6fff31d7aada25"
  }
];
